apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels: 
    app: orders
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: orders
  template: 
    metadata: 
      labels: 
        app: orders
    spec: 
      containers: 
      - name: orders
        image: mansi17/orders:microservices2
        ports:
        - containerPort: 8081