apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels: 
    app: user
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: user
  template: 
    metadata: 
      labels: 
        app: user
    spec: 
      containers: 
      - name: user
        image: mansi17/user:microservices2
        ports:
        - containerPort: 8080